apps/myblog/urls.py
from django.conf.urls import url

from . import views

app_name = "myblog"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_blog$', views.upload_blog, name='upload_blog'),
    url(r'^blog_detail/(?P<blog_info_id>[0-9]+)$', views.blog_detail, name="blog_detail"),
    url(r'^blog_list', views.blog_list, name='blog_list'),
    url(r'^edit_blog', views.blog_edit, name='edit_blog'),
    url(r'^add_blog_tag', views.add_blog_tag, name='add_blog_tag'),
    url(r'^about', views.about, name='about')
]

apps/tag_manage/urls.py
from django.conf.urls import url

from . import views

app_name = "tag_manage"
urlpatterns = [
    url(r'^$', views.tag_list, name='tag_list'),
    url(r'^add_tag$', views.add_list, name='add_tag')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # 默认目录
    url(r'^', include('apps.myblog.urls')),
    url(r'^tag/', include('apps.tag_manage.urls')),
    url(r'^user/', include('apps.user_manage.urls')),

    # 管理目录
    url(r'^admin/', admin.site.urls),
    # robots.txt文件
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # 站点地图
    url(r'^sitemap\.txt$', TemplateView.as_view(template_name='sitemap.txt', content_type='text/plain')),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

apps/tag_manage/models.py
from django.db import models
from ..base.models import BaseModel


class Tag(BaseModel):
    tag_name = models.CharField(max_length=20)

    #标签的优先级
    priority = models.IntegerField(default=0, db_index=True)

apps/tag_manage/forms.py
from django import forms


class AddTagForm(forms.Form):

    tag_name = forms.CharField(max_length=20, label="标签名", required=True)
    priority = forms.ChoiceField(label="优先级", choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3")])

apps/tag_manage/views.py
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import AddTagForm
from .models import Tag
from ..base.views import render_with_public_item


# Create your views here.


def tag_list(request):
    return render_with_public_item(request, "tag_manage/tag_list.html")


@permission_required('tag_manage.tag.add', login_url='/user/login')
def add_list(request):
    if request.method == 'POST':
        form = AddTagForm(request.POST)
        if form.is_valid():
            tag = Tag()
            tag.tag_name = form.data.get('tag_name')
            tag.priority = form.data.get('priority')
            tag.save()
            return HttpResponseRedirect('/tag')
    else:
        form = AddTagForm()
    return render(request, 'tag_manage/add_tag.html', {'form': form})

apps/tag_manage/templates/tag_manage/add_tag.html
{% extends "base.html" %}
{% block title %}
    新增标签
{% endblock %}
{% block content %}
    <form action="{% url 'tag_manage:add_tag' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load bootstrap %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">提交</button>
    </form>
{% endblock %}

apps/tag_manage/templates/tag_manage/tag_list.html
{% extends "myblog/blog_base.html" %}
{% block title %}
    所有标签
{% endblock %}
{% block blog_content %}
    {% if perms.tag.add %}
    <div class="row">
        <a href="{% url "tag_manage:add_tag" %}" class="btn bg-primary">添加标签</a>
    </div>
    {% endif %}
    <hr/>
    <div class="row">
        <div class="container-fluid"> {% for tag in tag_list %}
            <a href="/blog_list?tag={{ tag.id }}" class="btn btn-default {% if tag.priority == 0 %}btn-lg{% elif tag.priority == 2 %}btn-sm{% elif tag.priority == 3%}btn-xs{% endif %}">
                {{ tag.tag_name }}
            </a>
        {% endfor %}
        </div>
    </div>
{% endblock %}