apps/myblog/urls.py
from django.conf.urls import url

from . import views

app_name = "myblog"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_blog$', views.upload_blog, name='upload_blog'),
    url(r'^blog_detail/(?P<blog_info_id>[0-9]+)$', views.blog_detail, name="blog_detail"),
    url(r'^blog_list', views.blog_list, name='blog_list'),
    url(r'^edit_blog', views.blog_edit, name='edit_blog'),
    url(r'^add_blog_tag', views.add_blog_tag, name='add_blog_tag'),
    url(r'^about', views.about, name='about')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # 默认目录
    url(r'^', include('apps.myblog.urls')),
    url(r'^tag/', include('apps.tag_manage.urls')),
    url(r'^user/', include('apps.user_manage.urls')),

    # 管理目录
    url(r'^admin/', admin.site.urls),
    # robots.txt文件
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # 站点地图
    url(r'^sitemap\.txt$', TemplateView.as_view(template_name='sitemap.txt', content_type='text/plain')),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

apps/myblog/models.py
from django.db import models
from ..base.models import BaseModel
from ..user_manage.models import User
from ..tag_manage.models import Tag


class BlogInfo(BaseModel):
    title = models.CharField(max_length=255, default='')
    author = models.CharField(max_length=50, default='')
    abstract = models.CharField(max_length=500, default='')
    file_path = models.CharField(max_length=255, default='')
    comment_count = models.IntegerField(default=0)
    cover_img = models.CharField(max_length=255, default='default.png')
    favor_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    click_count = models.IntegerField(default=0, db_index=True)


class BlogComment(BaseModel):
    blog_info = models.ForeignKey(BlogInfo, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User)
    content = models.TextField(default='')
    reply_comment = models.ForeignKey('self', on_delete=models.CASCADE)


class BlogTagRelation(BaseModel):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    blog_info = models.ForeignKey(BlogInfo, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("tag", "blog_info")  # 这是重点

apps/myblog/forms.py
from django import forms
from django.forms import CheckboxSelectMultiple, Textarea

from ..tag_manage.models import Tag


class UploadBlogForm(forms.Form):

    title = forms.CharField(max_length=255, label="标题")
    abstract = forms.CharField(max_length=500, label="简介", widget=Textarea())
    file = forms.FileField(label="博客文件")
    file_name = forms.CharField(max_length=255, label="文件名")
    cover_img = forms.FileField(required=False, label="封面图")


class AddBlogTagForm(forms.Form):
    blog_id = forms.IntegerField(label="文章id")
    tags = forms.MultipleChoiceField(label="标签", widget=CheckboxSelectMultiple())

    def __init__(self, *args, **kwargs):
        super(self.__class__, self).__init__(*args, **kwargs)
        all_tags = Tag.objects.filter(deleted=False).order_by("priority")
        tag_choices = [(tag.id, tag.tag_name) for tag in all_tags]
        self.fields['tags'].choices = tag_choices


class EditBlogForm(forms.Form):
    blog_id = forms.IntegerField(label="文章id", required=False)
    title = forms.CharField(min_length=1, max_length=255, label="标题")
    abstract = forms.CharField(min_length=10, max_length=500, label="简介", widget=Textarea())
    file_name = forms.CharField(min_length=1, max_length=255, label="文件名")
    #cover_img = forms.FileField(required=False, label="封面图")
    content = forms.CharField(widget=Textarea(), min_length=10)

    def readonly_field(self, field_list):
        for field in field_list:
            self.fields[field].widget.attrs['readonly'] = True

apps/myblog/views.py
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django_redis import get_redis_connection

from .forms import UploadBlogForm, AddBlogTagForm, EditBlogForm
from .models import *
from .settings import *
from ..base.utils import *
from ..base.views import render_with_public_item


# Create your views here.
def index(request):
    return render_with_public_item(request, 'myblog/index.html')

def about(request):
    return render_with_public_item(request, 'myblog/about.html')


@permission_required('myblog.blog_info.add', login_url='/user/login')
def upload_blog(request):
    if request.method == 'POST':
        form = UploadBlogForm(request.POST, request.FILES)
        if form.is_valid():
            file_name = form.data.get('file_name')
            save_file(request.FILES['file'], os.path.join(BLOG_FILE_PATH, file_name))
            blog_info = BlogInfo()
            if 'cover_img' in request.FILES:
                img_fd = request.FILES['cover_img']
                img_name = md5(img_fd)
                save_file(img_fd, os.path.join(BLOG_COVER_PATH, img_name))
                blog_info.cover_img = img_name

            blog_info.file_path = file_name
            blog_info.title = form.data.get('title')
            blog_info.abstract = form.data.get('abstract')
            blog_info.author = request.user.username
            blog_info.save()

            site_map_add_url("http://blog.hellowood.net/blog_detail/%d" % blog_info.id)

            return HttpResponseRedirect("/blog_detail/%d" % blog_info.id)
    else:
        form = UploadBlogForm()
    return render(request, 'myblog/upload_blog.html', {'form': form})


def blog_detail(request, blog_info_id):
    blog_info = get_object_or_404(BlogInfo, pk=blog_info_id)
    blog_file_path = os.path.join(BLOG_FILE_PATH, blog_info.file_path)
    blog_content = read_file_to_string(blog_file_path)
    tag_relations = BlogTagRelation.objects.filter(deleted=False).filter(blog_info_id=blog_info.id)
    tags = [tag.tag for tag in tag_relations]
    redis_client = get_redis_connection()
    redis_client.incr("%s%s" % (BLOG_CLICK_PREFIX, blog_info_id))

    return render_with_public_item(request, 'myblog/blog_detail.html',
                                   {
                                       'blog': {
                                           'title': blog_info.title,
                                           'author': blog_info.author,
                                           'content': blog_content,
                                           'cover_img': blog_info.cover_img,
                                           'favor_count': blog_info.favor_count,
                                           'dislike_count': blog_info.dislike_count,
                                           'blog_info_id': blog_info_id,
                                           'url': request.get_full_path(),
                                           'tags': tags,
                                           'click_count': blog_info.click_count + 1,
                                       },
                                   })


def blog_list(request):
    if 'tag' in request.GET:
        blog_info_list = BlogInfo.objects.order_by("-created"). \
            filter(blogtagrelation__tag_id=request.GET['tag'])
    else:
        blog_info_list = BlogInfo.objects.order_by("-created")

    paginator = Paginator(blog_info_list, 5)  # Show 25 contacts per page

    if 'page' in request.GET:
        page = request.GET['page']
    else:
        page = 1

    try:
        blog_page_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        blog_page_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        blog_page_list = paginator.page(paginator.num_pages)

    current_page = blog_page_list.number
    total_page = blog_page_list.paginator.num_pages
    first_page = current_page - 4 if current_page - 4 > 1 else 1
    last_page = current_page + 4 if current_page + 4 < total_page else total_page

    return render_with_public_item(request, 'myblog/blog_list.html',
                                   {'blog_list': blog_page_list,
                                    'page_range': range(first_page, last_page + 1),
                                    })


@permission_required("myblog.blog_tag_relation.add", login_url="/user/login")
def add_blog_tag(request):
    if request.method == 'POST':
        form = AddBlogTagForm(request.POST)
        if form.is_valid():
            blog_id = request.POST['blog_id']
            tag_ids = request.POST.getlist('tags')
            tags = BlogTagRelation.objects.filter(deleted=False).filter(blog_info_id=blog_id)
            tag_old_ids = [x.tag_id for x in tags]
            for tag_new_id in tag_ids:
                if int(tag_new_id) not in tag_old_ids:
                    BlogTagRelation(tag_id=tag_new_id, blog_info_id=blog_id).save()

            return HttpResponseRedirect("/blog_detail/%s" % blog_id)
    else:
        if 'blog_id' not in request.GET:
            raise Http404("需要博客id!")
        blog_id = request.GET['blog_id']
        tags = Tag.objects.filter(deleted=False).filter(blogtagrelation__blog_info_id=blog_id)
        tag_ids = [x.id for x in tags]
        form = AddBlogTagForm(initial={"tags": tag_ids, "blog_id": blog_id})
    return render(request, 'myblog/add_blog_tag.html', {'form': form})


@permission_required(["myblog.blog_info.add", "myblog.blog_info.update"], login_url="/user/login")
def blog_edit(request):
    if request.method == 'POST':
        form = EditBlogForm(request.POST, request.FILES)
        if form.is_valid():
            if request.POST['blog_id']:
                blog_info = get_object_or_404(BlogInfo, pk=request.POST['blog_id'])
            else:
                blog_info = BlogInfo()
            blog_info.title = request.POST['title']
            blog_info.abstract = request.POST['abstract']
            # if 'cover_img' in request.FILES:
            #     img_fd = request.FILES['cover_img']
            #     img_name = md5(img_fd)
            #     save_file(img_fd, os.path.join(BLOG_COVER_PATH, img_name))
            #     blog_info.cover_img = img_name

            blog_file_path = os.path.join(BLOG_FILE_PATH, request.POST['file_name'])
            write_file(blog_file_path, request.POST['content'])
            blog_info.file_path = request.POST['file_name']
            blog_info.save()
            return HttpResponseRedirect("/blog_detail/%d" % blog_info.id)
    else:
        form = EditBlogForm()

        if 'blog_id' in request.GET:
            blog_info = get_object_or_404(BlogInfo, pk=request.GET['blog_id'])
            blog_file_path = os.path.join(BLOG_FILE_PATH, blog_info.file_path)
            blog_content = read_file_to_string(blog_file_path)
            form.initial = {"blog_id": blog_info.id,
                            "file_name": blog_info.file_path,
                            "title": blog_info.title,
                            "abstract": blog_info.abstract,
                            "content": blog_content
                            }
            form.readonly_field(['blog_id', 'file_name'])

    return render(request, 'myblog/blog_edit.html', {"form": form})

apps/myblog/templates/myblog/about.html
{% extends 'myblog/blog_base.html' %}
{% block blog_stylesheet %}
    {% load static %}
    <link href="{% static 'public/css/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    <style>
        .fa-hover a {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            display: block;
            color: #222;
            line-height: 32px;
            height: 32px;
            padding-left: 10px;
            border-radius: 4px;
        }

        .fa-hover a .fa {
            width: 32px;
            font-size: 20px;
            display: inline-block;
            text-align: right;
            margin-right: 10px
        }

        .fa-hover a:hover {
            background-color: #1d9d74;
            color: #fff;
            text-decoration: none
        }

        .fa-hover a:hover .fa {
            font-size: 28px;
            vertical-align: -6px
        }

        .fa-hover a:hover .text-muted {
            color: #bbe2d5
        }
    </style>
{% endblock %}


{% block title %}
    关于
{% endblock %}

{% block blog_content %}
    <h3>wood，后端开发，杭州</h3>
    <hr/>

    <div class="fa-hover">
        <a href="https://github.com/hello-wood" target="_blank">
            <i class="fa fa-fw fa-github"></i>
            hello-wood
        </a>
    </div>
{% endblock %}

apps/myblog/templates/myblog/add_blog_tag.html
{% extends "base.html" %}
{% block title %}
    设置博客标签
{% endblock %}
{% block content %}
    <form action="{% url 'myblog:add_blog_tag' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load bootstrap %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">设置</button>
    </form>
{% endblock %}

apps/myblog/templates/myblog/blog_base.html
{% extends 'base.html' %}

{% block metadata %}
    <meta http-equiv="x-dns-prefetch-control" content="on">
    {% block blog_metadata %}
    {% endblock %}
{% endblock %}

{% block stylesheet %}
    {% load static %}
    <link href="{% static 'myblog/css/blog_base.css' %}" rel="stylesheet">
    <link rel="dns-prefetch" href="//static.duoshuo.com">
    {% block blog_stylesheet %}
    {% endblock %}
{% endblock %}
{% block script %}
    <script type="text/javascript">
    $(".blog-content img").addClass('img-responsive');
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8 blog-content" id="blog_content">
        {% block blog_content %}
        {% endblock %}
    </div>
    <div class="col-md-4">
        {% block side_bar %}
        {% endblock %}
        <div class="panel panel-success nav-panel">
            <div class="panel-heading">
                <h3 class="panel-title">最热文章</h3>
            </div>
            {% if hotest_blog_list %}
                <ul class="list-group">
                    {% for blog in hotest_blog_list %}
                        <a href="{% url 'myblog:blog_detail' blog.id %}" class="list-group-item">
                            {{ blog.title }}
                        </a>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="panel panel-success nav-panel">
            <div class="panel-heading">
                <h3 class="panel-title">最新文章</h3>
            </div>
            {% if newest_blog_list %}
                <ul class="list-group">
                    {% for blog in newest_blog_list %}
                        <a href="{% url 'myblog:blog_detail' blog.id %}" class="list-group-item">
                            {{ blog.title }}
                        </a>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
        <div class="panel panel-success nav-panel">
            <div class="panel-heading">
                <h3 class="panel-title">最新评论</h3>
            </div>
            <!-- 多说最新评论 start -->
            <div class="ds-recent-comments" data-num-items="5" data-show-avatars="1" data-show-time="1" data-show-title="1" data-show-admin="1" data-excerpt-length="70"></div>
            <!-- 多说最新评论 end -->
            <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
            <script type="text/javascript">
                var duoshuoQuery = {short_name:"hellowood"};
                (function() {
                    var ds = document.createElement('script');
                    ds.type = 'text/javascript';ds.async = true;
                    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                    ds.charset = 'UTF-8';
                    (document.getElementsByTagName('head')[0]
                    || document.getElementsByTagName('body')[0]).appendChild(ds);
                })();
            </script>
            <!-- 多说公共JS代码 end -->
        </div>
    </div>
</div>
{% endblock %}

apps/myblog/templates/myblog/blog_detail.html
{% extends 'myblog/blog_base.html' %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block blog_stylesheet %}
    {% load static %}
    <link href="{% static 'myblog/css/pygments-friendly.css' %}" rel="stylesheet">
    <link href="{% static 'myblog/css/blog_detail.css' %}" rel="stylesheet">
{% endblock %}

{% block blog_content %}
    <h2>{{ blog.title }}</h2>
    {% if blog.author %}
        <div style="text-align: right">
            <h4>作者： <strong>{{ blog.author }}</strong></h4>
        </div>
    {% endif %}
    <span class="glyphicon glyphicon-eye-open" aria-hidden="true"
          style="margin-right: 5px;">&nbsp;{{ blog.click_count }}</span>
    &emsp;
    {% if blog.tags %}
        <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
        {% for tag in blog.tags %}
            <a class="btn btn-default btn-xs" href="/blog_list?tag={{ tag.id }}">{{ tag.tag_name }}</a>
        {% endfor %}
    {% endif %}
    <hr style="margin-top: 5px; margin-bottom: 2px"/>
    {% load myTag %}
    <div class="panel panel-default">
        <div class="panel-body">
            {{ blog.content|markdown|safe }}
        </div>
    </div>

    <div class="row blog-comment">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="ds-share" data-thread-key="{{ blog.blog_info_id }}" data-title="{{ blog.title }}"
                     data-url="http://blog.hellowood.net{{ blog.url }}">
                    <div class="ds-share-inline">
                        <ul class="ds-share-icons-16">

                            <li data-toggle="ds-share-icons-more"><a class="ds-more" href="javascript:void(0);">分享到：</a>
                            </li>
                            <li><a class="ds-weibo" href="javascript:void(0);" data-service="weibo">微博</a></li>
                            <li><a class="ds-qzone" href="javascript:void(0);" data-service="qzone">QQ空间</a></li>
                            <li><a class="ds-qqt" href="javascript:void(0);" data-service="qqt">腾讯微博</a></li>
                            <li><a class="ds-wechat" href="javascript:void(0);" data-service="wechat">微信</a></li>

                        </ul>
                        <div class="ds-share-icons-more">
                        </div>
                    </div>
                </div>
                <!-- 多说评论框 start -->
                <div class="ds-thread" data-thread-key="{{ blog.blog_info_id }}" data-title="{{ blog.title }}"
                     data-url="http://blog.hellowood.net{{ blog.url }}"></div>
                <!-- 多说评论框 end -->
                <!-- 多说公共JS代码 start (一个网页只需插入一次) -->
                <script type="text/javascript">
                    var duoshuoQuery = {short_name: "hellowood"};
                    (function () {
                        var ds = document.createElement('script');
                        ds.type = 'text/javascript';
                        ds.async = true;
                        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
                        ds.charset = 'UTF-8';
                        (document.getElementsByTagName('head')[0]
                        || document.getElementsByTagName('body')[0]).appendChild(ds);
                    })();
                </script>
                <!-- 多说公共JS代码 end -->
            </div>
        </div>
    </div>

{% endblock %}

{% block side_bar %}
    <div class="panel panel-success nav-panel">
        <div class="panel-heading">
            <h4 class="panel-title">标签</h4>
        </div>
        <div class="panel-body">
            <div class="container-fluid"> {% for tag in tag_list %}
                <a href="/blog_list?tag={{ tag.id }}"
                   class="btn btn-default {% if tag.priority == 0 %}btn-lg{% elif tag.priority == 2 %}btn-sm{% elif tag.priority == 3 %}btn-xs{% endif %}">
                    {{ tag.tag_name }}
                </a>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

apps/myblog/templates/myblog/blog_edit.html
{% extends "base.html" %}

{% block title %}
    编辑博客
{% endblock %}


{% block content %}
    <form action="{% url 'myblog:edit_blog' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load bootstrap %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">保存修改</button>
    </form>
{% endblock %}

apps/myblog/templates/myblog/blog_list.html
{% extends 'myblog/blog_base.html' %}

{% block title %}
    全部博客
{% endblock %}

{% block blog_content %}
    {% if perms.bloginfo.add %}
    <div class="row" style="text-align: right">
        <a class="btn bg-primary" href="{% url "myblog:upload_blog" %}">上传博客</a>
    </div>
    <hr/>
    {% endif %}
    <h3>全部博客</h3>
    <hr/>
    <div class="list-group">
        {% load myTag %}
        {% for blog in blog_list %}
        <div class="row list-group-item" style="padding-bottom: 50px;border: 0;">
            <span>
                <a href="{% url 'myblog:blog_detail' blog.id  %}">
                    <h4 class="list-group-item-heading">{{ blog.title }}</h4>
                    <span style="float: right">{{ blog.created | date:"发布于：Y年m月d日" }}</span>
                </a>
            </span>
            <div style="margin: 5px">
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true">&nbsp;{{ blog.click_count }}</span>
                &emsp;
                {% if blog.blogtagrelation_set.all %}
                    <span class="glyphicon glyphicon-tags" aria-hidden="true"></span>
                    {% for tag_relation in blog.blogtagrelation_set.all %}
                        <a class="btn btn-default btn-xs" href="/blog_list?tag={{ tag_relation.tag.id }}">{{ tag_relation.tag.tag_name }}</a>
                    {% endfor %}
                {% endif %}
            </div>
            {% if perms.bloginfo.add %}
                <div class="col-md-9">
                    <p style="min-height: 30px;" class="list-group-item-text">{{ blog.abstract | truncate_chars:125 }}</p>
                </div>
                <div class="col-md-3">
                    <div class="row">
                    </div>
                    <div class="row" style="text-align: right">
                        <a class="btn bg-primary" href="/edit_blog?blog_id={{ blog.id }}">编辑</a>
                        <a class="btn bg-primary" href="/add_blog_tag?blog_id={{ blog.id }}">设置博客标签</a>
                    </div>
                </div>
            {% else %}
                <p style="min-height: 30px;" class="list-group-item-text">{{ blog.abstract | truncate_chars:125 }}</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if blog_list.has_previous %}
                <li>
                    <a href="/blog_list?page={{blog_list.previous_page_number}}" aria-label="上一页">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}
            {% for i in page_range  %}
                <li {%if i == blog_list.number %}class="active"{% endif %}><a href="/blog_list?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if blog_list.has_next %}
                <li>
                    <a href="/blog_list?page={{ blog_list.next_page_number }}" aria-label="下一页">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}
{% block side_bar %}
    <div class="panel panel-success nav-panel">
        <div class="panel-heading">
            <h4 class="panel-title">标签</h4>
        </div>
        <div class="panel-body">
            <div class="container-fluid"> {% for tag in tag_list %}
                <a href="/blog_list?tag={{ tag.id }}" class="btn btn-default {% if tag.priority == 0 %}btn-lg{% elif tag.priority == 2 %}btn-sm{% elif tag.priority == 3%}btn-xs{% endif %}">
                    {{ tag.tag_name }}
                </a>
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

apps/myblog/templates/myblog/index.html
{% extends "base.html" %}

{% block title %}
    首页
{% endblock %}

{% block stylesheet %}
    {% load static %}
    <link href="{% static 'myblog/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <p class="lead"><br/>
        </p>
    </div>

    <div class="row marketing">
        <div class="col-md-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title">最新博客</h4>
                </div>
                {% if newest_blog_list %}
                    <ul class="list-group">
                        {% for blog in newest_blog_list %}
                            <a href="{% url 'myblog:blog_detail' blog.id %}" class="list-group-item">
                                {{ blog.title }}
                            </a>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title">标签</h4>
                </div>
                <div class="panel-body">
                    <div class="container-fluid">
                        {% for tag in tag_list %}
                            <a href="/blog_list?tag={{ tag.id }}" class="btn btn-default {% if tag.priority == 0 %}btn-lg{% elif tag.priority == 2 %}btn-sm{% elif tag.priority == 3%}btn-xs{% endif %}">
                                {{ tag.tag_name }}
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h4 class="panel-title">热门博客</h4>
                </div>
                {% if hotest_blog_list %}
                    <ul class="list-group">
                        {% for blog in hotest_blog_list %}
                            <a href="{% url 'myblog:blog_detail' blog.id %}" class="list-group-item">
                                {{ blog.title }}
                            </a>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

apps/myblog/templates/myblog/upload_blog.html
{% extends 'base.html' %}

{% block title %}
博客上传
{% endblock %}

{% block content %}
    <form action="{% url 'myblog:upload_blog' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load bootstrap %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">提交</button>
    </form>
{% endblock %}