apps/myblog/urls.py
from django.conf.urls import url

from . import views

app_name = "myblog"
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_blog$', views.upload_blog, name='upload_blog'),
    url(r'^blog_detail/(?P<blog_info_id>[0-9]+)$', views.blog_detail, name="blog_detail"),
    url(r'^blog_list', views.blog_list, name='blog_list'),
    url(r'^edit_blog', views.blog_edit, name='edit_blog'),
    url(r'^add_blog_tag', views.add_blog_tag, name='add_blog_tag'),
    url(r'^about', views.about, name='about')
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # 默认目录
    url(r'^', include('apps.myblog.urls')),
    url(r'^tag/', include('apps.tag_manage.urls')),
    url(r'^user/', include('apps.user_manage.urls')),

    # 管理目录
    url(r'^admin/', admin.site.urls),
    # robots.txt文件
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # 站点地图
    url(r'^sitemap\.txt$', TemplateView.as_view(template_name='sitemap.txt', content_type='text/plain')),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

apps/base/models.py
from django.db import models


class BaseModel(models.Model):
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    deleted = models.BooleanField(default=False, db_index=True)

    class Meta:
        abstract = True

apps/base/views.py
from ..myblog.models import BlogInfo
from ..tag_manage.models import Tag
from django.shortcuts import render, get_object_or_404, get_list_or_404, render_to_response


def render_with_public_item(request, page, data=None):
    newest_bloginfo_list = BlogInfo.objects.order_by("-created")[0:5]
    hotest_bloginfo_list = BlogInfo.objects.order_by("-click_count")[0:5]
    tags = get_list_or_404(Tag.objects.filter(deleted=False))

    if data is None:
        data = {}

    data.update({
        'newest_blog_list': [{"id": blog.id, "title": blog.title} for blog in newest_bloginfo_list],
        'hotest_blog_list': [{"id": blog.id, "title": blog.title} for blog in hotest_bloginfo_list],
        'tag_list': tags
    })

    return render(request, page, data)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block metadata %}{% endblock %}
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="wood's blog">
    <meta name="author" content="wood">
    {% load static %}
    <link rel="icon" href="{% static 'public/img/favicon.ico' %}">

    <title>{% block title %}{% endblock %}</title>

    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'public/css/base.css' %}" rel="stylesheet">

    {% block stylesheet %}{% endblock %}
</head>

<body>


<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'myblog:index' %}">Hello Wood</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% load myTag %}
                {% navtagitem / "主页" %}
                {% navtagitem /blog_list "博客" %}
                {% navtagitem /tag "标签" %}
                {% navtagitem /about "关于" %}
{% comment %}                <li><a href="#contact">记一笔</a></li>
                <li><a href="#contact">小工具</a></li>{% endcomment %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<footer class="footer">
    <div class="container">
        <p>Copyright © 2010-2016 WOOD'S BLOG - All Rights Reserved. </p>
    </div>
</footer>

<script type="text/javascript" src="{% static 'jquary/jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<script type="text/javascript">
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>
{% block script %}{% endblock %}
</body>
</html>